### PR TITLE
replace call to print with logging.debug

### PR DESCRIPTION
**Pull request by tinnet**
quick fix for py3 compatibility :)

### CODE REVIEW

**Comment by jvanasco** [comment]
Wow.  That should have been a debug for other reasons too.  Thanks for catching.  Will approve and bump a new release Monday or Tuesday.

**Comment by tinnet** [comment]
Cool, thanks for getting a new version out quickly, I hate having `-e git:/` lines in my requirements files :)

On another note: I tried to make the most minimal change possible here, but if you are interested I can follow it up with a PR that goes over the various pylint warnings in the project?

**Comment by jvanasco** [comment]
This is merged into the `0.0.5` tag and release on pypi (09/08/2015, 11:04am est)

what sort of warnings are you seeing in pylint that worry you?  this passes my flake8 checks -- though I have a handful of settings regarding line length and bracket formatting turned off.

**Comment by tinnet** [comment]
thanks! :)

most of the warnings are about the single letter variable names I think (i'm at the non-python day job right now, can't check). But if you are not bothered -> let's not touch a running system :)

**Pull request merged**
