### PR TITLE
Prevents AttributeError when no current request.

### PR DESCRIPTION
**Pull request by saebyn**

### CODE REVIEW

**Comment by jvanasco** [comment]
This looks fine to merge.  One question - when do you not have a request?  Is this caused by a testing suite?

**Comment by saebyn** [comment]
I have a class with a method that is cached by dogpile that is used in several Pyramid views and also in a WSGI middleware.

**Comment by jvanasco** [comment]
Ah.  That's an odd use case!

Merged and uploaded to pypi.  The release version is pyramid_debugtoolbar_dogpile==0.0.3

**Comment by saebyn** [comment]
Thanks!

**Pull request merged**
